### ISSUE TITLE
setRules

### ISSUE THREAD

**Issue by davak** [grocerycrud/documentation#1]
I don't find a setRules() function in GroceryCrud.php.  The setRule() function is there. 

I'm a rookie, so forgive me if the mistake is on me.

**Comment by scoumbourdis** [comment]
Hello @davak ,

setRules is only available on Grocery CRUD Enterprise. I've updated the documentation. The only way to define it for now is the little icon at the left on the menu. I will try to change that at the future so it will be more clear to the developer.

Regards
Johnny
