### ISSUE TITLE
any way to get older documentation locally

### ISSUE THREAD

**Issue by mckaygerhard** [grocerycrud/documentation#3]
there's any way to get older documentation locally, in markdown preferable! cos i still using CI2 (i have my own improved supported version) and also in CI3 ..

**Comment by scoumbourdis** [comment]
Unfortunately, we don't. The main reason that I've created the new documentation was to have a publicly available documentation on github as a markdown that is easy to contribute and download locally.

**Comment by mckaygerhard** [comment]
and how the older one was generated?
